#version 430 core

layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;
layout(binding = 0, rgba32f) uniform image2D scene_image;

void main() {
    ivec2 pixelPos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 res = imageSize(scene_image);
    if (pixelPos.x >= res.x || pixelPos.x < 0 || pixelPos.y >= res.y || pixelPos.y < 0) {
        return;
    }

    imageStore(scene_image, pixelPos, vec4(0.f, 1.f, 0.f, 1.f));
}